### ISSUE TITLE
Not releasing file handles

### ISSUE THREAD

**Issue by jarednielsen** [ex4sperans/mag#4]
I combined `mag` with `hyperopt` and ran 5000 experiments (various hyperparameter configurations) on MNIST. This was all done synchronously through a single Python process (no forking or subprocess calls). After 335 experiments, it crashed.

`OSError: [Errno 24] Too many open files`

Does `mag` properly release file handles after it's done with them? I'm using Python's `with` context manager protocol and only handling one experiment at a time, so how can I fix this error?

**Comment by ex4sperans** [comment]
Hi! Thank you for your feedback.

I've just run 10k experiments in a loop and got no errors.

I also used [psutil](https://github.com/giampaolo/psutil) to check if there are some unreleased file handles as you. For my case, `psutil` shows only a single file opened during each experiment, and it's always just a log file, which is expected. In the end of the program `psutil` shows no opened files.

Could you please try reproduce the behavior you mentioned with included `psutil` monitoring? It's just three lines of code:

```
import psutil
p = psutil.Process()
print(p.open_files())
```

Looking forward to see your response :)

Regards,

Dmitriy

**Comment by jarednielsen** [comment]
Repeating my experiment, there are only 0 or 1 files open at any one time during the first 10 iterations. Must've been some other wonky bug; thanks for the response!
